version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: simple_laravel_api
    volumes:
      - ./:/var/www/simple_laravel_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    working_dir: /var/www/simple_laravel_api
    restart: unless-stopped
    environment:
      SERVICE_NAME: simple_laravel_api
      QUEUE_CONNECTION: database
      APP_NAME: simple_laravel_api
      DB_CONNECTION: mysql
      DB_DRIVER: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: demo
      DB_USERNAME: root
      DB_PASSWORD: demo_password
    networks:
      - app_network

  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: demo_password
      MYSQL_PASSWORD: demo_password
      MYSQL_USER: demo_user
    ports:
      - "3306:3306"
    volumes:
      - "./storage/db-data:/var/lib/mysql"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
